// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace InsideWordMVCWeb.Controllers {
    public partial class AdminController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AdminController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult _GetJqGridMemberList() {
            return new T4MVC_JsonResult(Area, Name, ActionNames._GetJqGridMemberList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult _EditJqGridMember() {
            return new T4MVC_JsonResult(Area, Name, ActionNames._EditJqGridMember);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult CategoryEdit() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.CategoryEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult _GetJqGridCommentList() {
            return new T4MVC_JsonResult(Area, Name, ActionNames._GetJqGridCommentList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult _EditJqGridComment() {
            return new T4MVC_ActionResult(Area, Name, ActionNames._EditJqGridComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult _GetJqGridArticleList() {
            return new T4MVC_JsonResult(Area, Name, ActionNames._GetJqGridArticleList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult _EditJqGridArticle() {
            return new T4MVC_JsonResult(Area, Name, ActionNames._EditJqGridArticle);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminController Actions { get { return MVC.Admin; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Admin";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string SettingsManagement = "SettingsManagement";
            public readonly string Member = "Member";
            public readonly string _GetJqGridMemberList = "_GetJqGridMemberList";
            public readonly string _EditJqGridMember = "_EditJqGridMember";
            public readonly string Category = "Category";
            public readonly string CategoryEdit = "CategoryEdit";
            public readonly string Conversation = "Conversation";
            public readonly string _GetJqGridCommentList = "_GetJqGridCommentList";
            public readonly string _EditJqGridComment = "_EditJqGridComment";
            public readonly string Article = "Article";
            public readonly string _GetJqGridArticleList = "_GetJqGridArticleList";
            public readonly string _EditJqGridArticle = "_EditJqGridArticle";
            public readonly string RefreshArticle = "RefreshArticle";
            public readonly string RefreshArticleStatus = "RefreshArticleStatus";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Article = "~/Views/Admin/Article.aspx";
            public readonly string Category = "~/Views/Admin/Category.aspx";
            public readonly string CategoryEdit = "~/Views/Admin/CategoryEdit.aspx";
            public readonly string Conversation = "~/Views/Admin/Conversation.aspx";
            public readonly string Index = "~/Views/Admin/Index.aspx";
            public readonly string Member = "~/Views/Admin/Member.aspx";
            public readonly string RefreshArticle = "~/Views/Admin/RefreshArticle.ascx";
            public readonly string SettingsManagement = "~/Views/Admin/SettingsManagement.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_AdminController: InsideWordMVCWeb.Controllers.AdminController {
        public T4MVC_AdminController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SettingsManagement() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SettingsManagement);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SettingsManagement(InsideWordMVCWeb.ViewModels.Admin.SettingsManagementVM model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SettingsManagement);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Member() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Member);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult _GetJqGridMemberList(InsideWordMVCWeb.ViewModels.Admin.MemberManagementFilterVM filter) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames._GetJqGridMemberList);
            callInfo.RouteValueDictionary.Add("filter", filter);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult _EditJqGridMember(InsideWordMVCWeb.ViewModels.Admin.EditMemberManagementVM model) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames._EditJqGridMember);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Category() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Category);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Category(System.Collections.Generic.IList<InsideWordMVCWeb.ViewModels.Shared.NumBitVM> model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Category);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CategoryEdit(long? categoryId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CategoryEdit);
            callInfo.RouteValueDictionary.Add("categoryId", categoryId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CategoryEdit(InsideWordMVCWeb.ViewModels.Admin.CategoryEditVM model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CategoryEdit);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Conversation() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Conversation);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult _GetJqGridCommentList(InsideWordMVCWeb.ViewModels.Admin.CommentManagementFilterVM filter) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames._GetJqGridCommentList);
            callInfo.RouteValueDictionary.Add("filter", filter);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult _EditJqGridComment(InsideWordMVCWeb.ViewModels.Admin.EditCommentManagementVM model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames._EditJqGridComment);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Article() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Article);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult _GetJqGridArticleList(InsideWordMVCWeb.ViewModels.Shared.ArticleFilterVM filter) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames._GetJqGridArticleList);
            callInfo.RouteValueDictionary.Add("filter", filter);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult _EditJqGridArticle(InsideWordMVCWeb.ViewModels.Shared.JqGridEditArticleVM model) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames._EditJqGridArticle);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RefreshArticle() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.RefreshArticle);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult RefreshArticle(InsideWordMVCWeb.ViewModels.Admin.RefreshArticleVM model) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.RefreshArticle);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult RefreshArticleStatus() {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.RefreshArticleStatus);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
