// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace InsideWordMVCWeb.Controllers {
    public partial class ArticleController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ArticleController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ArticleController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ArticleDetails() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ArticleDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ArticleEdit() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ArticleEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ArticleEditor() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ArticleEditor);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ArticleController Actions { get { return MVC.Article; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Article";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string ArticleDetails = "ArticleDetails";
            public readonly string ArticleEdit = "ArticleEdit";
            public readonly string ArticleEditor = "ArticleEditor";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string ArticleDetails = "~/Views/Article/ArticleDetails.aspx";
            public readonly string ArticleEdit = "~/Views/Article/ArticleEdit.aspx";
            public readonly string ArticleEditor = "~/Views/Article/ArticleEditor.ascx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ArticleController: InsideWordMVCWeb.Controllers.ArticleController {
        public T4MVC_ArticleController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult ArticleDetails(long articleId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ArticleDetails);
            callInfo.RouteValueDictionary.Add("articleId", articleId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ArticleEdit(long? articleId, string issuedKey) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ArticleEdit);
            callInfo.RouteValueDictionary.Add("articleId", articleId);
            callInfo.RouteValueDictionary.Add("issuedKey", issuedKey);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ArticleEditor(long? articleId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ArticleEditor);
            callInfo.RouteValueDictionary.Add("articleId", articleId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ArticleEditor(long? articleId, InsideWordMVCWeb.ViewModels.Article.ArticleEditorVM model, string submitType) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ArticleEditor);
            callInfo.RouteValueDictionary.Add("articleId", articleId);
            callInfo.RouteValueDictionary.Add("model", model);
            callInfo.RouteValueDictionary.Add("submitType", submitType);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
