// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace InsideWordMVCWeb.Controllers {
    public partial class ChildController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ChildController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ChildController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Article() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Article);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Blurb() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Blurb);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Conversation() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Conversation);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult EditPersonalInfo() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.EditPersonalInfo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult EditAlternateCategory() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.EditAlternateCategory);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ChildController Actions { get { return MVC.Child; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Child";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string MasterNavigationBar = "MasterNavigationBar";
            public readonly string MasterHeader = "MasterHeader";
            public readonly string MasterLoginModal = "MasterLoginModal";
            public readonly string Article = "Article";
            public readonly string Blurb = "Blurb";
            public readonly string Conversation = "Conversation";
            public readonly string Login = "Login";
            public readonly string LoginOpenId = "LoginOpenId";
            public readonly string LoginOpenIdProcess = "LoginOpenIdProcess";
            public readonly string Register = "Register";
            public readonly string EditPersonalInfo = "EditPersonalInfo";
            public readonly string EditAlternateCategory = "EditAlternateCategory";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string AddMedia = "~/Views/Child/AddMedia.ascx";
            public readonly string Article = "~/Views/Child/Article.ascx";
            public readonly string Blurb = "~/Views/Child/Blurb.ascx";
            public readonly string Comment = "~/Views/Child/Comment.ascx";
            public readonly string Conversation = "~/Views/Child/Conversation.ascx";
            public readonly string EditAlternateCategory = "~/Views/Child/EditAlternateCategory.ascx";
            public readonly string EditPersonalInfo = "~/Views/Child/EditPersonalInfo.ascx";
            public readonly string Login = "~/Views/Child/Login.ascx";
            public readonly string LoginOpenId = "~/Views/Child/LoginOpenId.ascx";
            public readonly string MasterHeader = "~/Views/Child/MasterHeader.ascx";
            public readonly string MasterLoginModal = "~/Views/Child/MasterLoginModal.ascx";
            public readonly string MasterNavigationBar = "~/Views/Child/MasterNavigationBar.ascx";
            public readonly string Register = "~/Views/Child/Register.ascx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ChildController: InsideWordMVCWeb.Controllers.ChildController {
        public T4MVC_ChildController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult MasterNavigationBar() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.MasterNavigationBar);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult MasterHeader() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.MasterHeader);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult MasterLoginModal() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.MasterLoginModal);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Article(InsideWordMVCWeb.ViewModels.ProviderViewModels.ArticleVM viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Article);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Blurb(InsideWordMVCWeb.ViewModels.ProviderViewModels.BlurbVM articleBlurb) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Blurb);
            callInfo.RouteValueDictionary.Add("articleBlurb", articleBlurb);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Conversation(InsideWordMVCWeb.ViewModels.ProviderViewModels.ConversationVM viewModel) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Conversation);
            callInfo.RouteValueDictionary.Add("viewModel", viewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Login() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Login);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult Login(InsideWordMVCWeb.ViewModels.Child.LoginVM model) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.Login);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LoginOpenId() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LoginOpenId);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult LoginOpenId(InsideWordMVCWeb.ViewModels.Child.LoginOpenIdVM model) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.LoginOpenId);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LoginOpenIdProcess() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LoginOpenIdProcess);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Register() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Register);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult Register(InsideWordMVCWeb.ViewModels.Child.RegisterVM model) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.Register);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditPersonalInfo(long memberId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditPersonalInfo);
            callInfo.RouteValueDictionary.Add("memberId", memberId);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult EditPersonalInfo(long memberId, InsideWordMVCWeb.ViewModels.Child.PersonalInfoVM model) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.EditPersonalInfo);
            callInfo.RouteValueDictionary.Add("memberId", memberId);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditAlternateCategory(long memberId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditAlternateCategory);
            callInfo.RouteValueDictionary.Add("memberId", memberId);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult EditAlternateCategory(long memberId, InsideWordMVCWeb.ViewModels.Child.AlternateCategoryListVM model) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.EditAlternateCategory);
            callInfo.RouteValueDictionary.Add("memberId", memberId);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
