// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace InsideWordMVCWeb.Controllers {
    public partial class MemberController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MemberController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected MemberController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ValidateEmail() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ValidateEmail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Delete() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ChangePassword() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ChangePassword);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Profile() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Profile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Account() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Account);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult _GetJqGridArticleList() {
            return new T4MVC_JsonResult(Area, Name, ActionNames._GetJqGridArticleList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult _EditJqGridArticle() {
            return new T4MVC_ActionResult(Area, Name, ActionNames._EditJqGridArticle);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult RequestValidateEmail() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.RequestValidateEmail);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MemberController Actions { get { return MVC.Member; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Member";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string EmailValidationSent = "EmailValidationSent";
            public readonly string RegisterComplete = "RegisterComplete";
            public readonly string ValidateEmail = "ValidateEmail";
            public readonly string Delete = "Delete";
            public readonly string ResetPasswordRequest = "ResetPasswordRequest";
            public readonly string ResetPasswordRequestComplete = "ResetPasswordRequestComplete";
            public readonly string ChangePassword = "ChangePassword";
            public readonly string ChangePasswordComplete = "ChangePasswordComplete";
            public readonly string Profile = "Profile";
            public readonly string Logout = "Logout";
            public readonly string Account = "Account";
            public readonly string _GetJqGridArticleList = "_GetJqGridArticleList";
            public readonly string _EditJqGridArticle = "_EditJqGridArticle";
            public readonly string RequestValidateEmail = "RequestValidateEmail";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Account = "~/Views/Member/Account.aspx";
            public readonly string ChangePassword = "~/Views/Member/ChangePassword.aspx";
            public readonly string Profile = "~/Views/Member/Profile.aspx";
            public readonly string ResetPassword = "~/Views/Member/ResetPassword.aspx";
            public readonly string ResetPasswordRequest = "~/Views/Member/ResetPasswordRequest.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_MemberController: InsideWordMVCWeb.Controllers.MemberController {
        public T4MVC_MemberController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult EmailValidationSent() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EmailValidationSent);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RegisterComplete() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.RegisterComplete);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ValidateEmail(string key) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ValidateEmail);
            callInfo.RouteValueDictionary.Add("key", key);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Delete(string key) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Delete);
            callInfo.RouteValueDictionary.Add("key", key);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ResetPasswordRequest() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ResetPasswordRequest);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ResetPasswordRequest(InsideWordMVCWeb.ViewModels.Member.ResetPasswordRequestVM model, bool captchaValid) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ResetPasswordRequest);
            callInfo.RouteValueDictionary.Add("model", model);
            callInfo.RouteValueDictionary.Add("captchaValid", captchaValid);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ResetPasswordRequestComplete() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ResetPasswordRequestComplete);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ChangePassword(string issuedKey) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ChangePassword);
            callInfo.RouteValueDictionary.Add("issuedKey", issuedKey);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ChangePassword(string issuedKey, InsideWordMVCWeb.ViewModels.Member.ChangePasswordVM model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ChangePassword);
            callInfo.RouteValueDictionary.Add("issuedKey", issuedKey);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ChangePasswordComplete() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ChangePasswordComplete);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Profile(long memberId, int? page) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Profile);
            callInfo.RouteValueDictionary.Add("memberId", memberId);
            callInfo.RouteValueDictionary.Add("page", page);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Logout() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Logout);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Account(long memberId, string issuedKey) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Account);
            callInfo.RouteValueDictionary.Add("memberId", memberId);
            callInfo.RouteValueDictionary.Add("issuedKey", issuedKey);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult _GetJqGridArticleList(long memberId, InsideWordMVCWeb.ViewModels.Member.AccountArticleFilterVM model) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames._GetJqGridArticleList);
            callInfo.RouteValueDictionary.Add("memberId", memberId);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult _EditJqGridArticle(InsideWordMVCWeb.ViewModels.Member.AccountEditArticleVM model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames._EditJqGridArticle);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RequestValidateEmail(string newEmail, long memberId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.RequestValidateEmail);
            callInfo.RouteValueDictionary.Add("newEmail", newEmail);
            callInfo.RouteValueDictionary.Add("memberId", memberId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
