// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace InsideWordMVCWeb.Controllers {
    public partial class SharedController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SharedController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SharedController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult Vote() {
            return new T4MVC_JsonResult(Area, Name, ActionNames.Vote);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddMedia() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AddMedia);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SharedController Actions { get { return MVC.Shared; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Shared";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Vote = "Vote";
            public readonly string AddMedia = "AddMedia";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string AddMedia = "~/Views/Shared/AddMedia.aspx";
            public readonly string AddMediaDone = "~/Views/Shared/AddMediaDone.aspx";
            public readonly string AddMediaStandalone = "~/Views/Shared/AddMediaStandalone.aspx";
            public readonly string Message = "~/Views/Shared/Message.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_SharedController: InsideWordMVCWeb.Controllers.SharedController {
        public T4MVC_SharedController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.JsonResult Vote(long articleId, long voteValue) {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.Vote);
            callInfo.RouteValueDictionary.Add("articleId", articleId);
            callInfo.RouteValueDictionary.Add("voteValue", voteValue);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddMedia(InsideWordMVCWeb.ViewModels.Shared.AddMediaVM.AddMediaPurpose purpose, InsideWordMVCWeb.ViewModels.Shared.AddMediaVM.AddMediaType type, long? memberId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddMedia);
            callInfo.RouteValueDictionary.Add("purpose", purpose);
            callInfo.RouteValueDictionary.Add("type", type);
            callInfo.RouteValueDictionary.Add("memberId", memberId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddMedia(InsideWordMVCWeb.ViewModels.Shared.AddMediaVM model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddMedia);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
